Repository COS301-SE-2024/Web-Exploration-Engine, pull requests merged in 2024-06, with the labels that each got.

#55 Feature/error message frontend
  wee/frontend/specs/component/Home.spec.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/components/NavBar.tsx
Labels: enhancement

#59 Feature/filter UI home page
  wee/frontend/src/app/(pages)/layout.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/tailwind.config.js
  wee/package-lock.json
  wee/package.json
Labels: enhancement

#58 Feature/authentication intergration
  .github/workflows/main.yaml
  wee/.gitignore
  wee/frontend/specs/component/Login.spec.tsx
  wee/frontend/specs/unit/auth.spec.tsx
  wee/frontend/src/app/(landing)/login/page.tsx
  wee/frontend/src/app/(landing)/signup/page.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/components/FlipWords.tsx
  wee/frontend/src/app/components/NavBar.tsx
  wee/frontend/src/app/models/AuthModels.ts
  wee/frontend/src/app/services/AuthService.ts
  wee/frontend/src/app/utils/supabase_anon_client.ts
  wee/frontend/src/app/utils/supabase_service_client.ts
  wee/package-lock.json
  wee/package.json
  wee/webscraper/src/main.ts
Labels: enhancement

#64 Demo 1 Documentation
  README.md
  documentation/coding-standards.md
Labels: documentation

#100 Feature/add pages add textarea
  wee/e2e/webscraper-e2e/src/webscraper/webscraper.spec.ts
  wee/frontend/specs/component/Home.spec.tsx
  wee/frontend/src/app/(pages)/faq/page.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
  wee/frontend/src/app/components/NavBar.tsx
Labels: enhancement

#114 Feature/scrape result page
  wee/frontend/specs/component/Home.spec.tsx
  wee/frontend/specs/component/Results.spec.tsx
  wee/frontend/src/app/(landing)/login/page.tsx
  wee/frontend/src/app/(landing)/signup/page.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
  wee/frontend/src/app/components/Graphs/BarChart.tsx
  wee/frontend/src/app/components/Graphs/PieChart.tsx
  wee/frontend/src/app/components/Graphs/RadialBar.tsx
  wee/frontend/src/app/components/Graphs/index.ts
  wee/frontend/src/app/components/ScrapeResultCard.tsx
  wee/frontend/src/app/components/Util/Input.tsx
  wee/frontend/src/app/components/Util/Pagination.tsx
  wee/frontend/src/app/components/Util/Select.tsx
  wee/frontend/src/app/components/chart.tsx
  wee/frontend/src/app/models/ChartModel.ts
  wee/package-lock.json
  wee/package.json
  wee/webscraper/src/unit-tests/read-robots-txt.test.ts
Labels: enhancement

#118 Feature/pagination UI improvements
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/components/Util/Textarea.tsx
  wee/frontend/src/app/components/chart.tsx
Labels: enhancement

#125 Hero Section Text
  wee/frontend/src/app/(pages)/page.tsx
Labels: implementation

#122 Feature/help popup fix
  wee/frontend/public/images/video-thumbnail.svg
  wee/frontend/src/app/(pages)/layout.tsx
  wee/frontend/src/app/components/HelpPopup.tsx
  wee/frontend/src/app/global.css
Labels: implementation

#127 Feature/resultcards to table
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/components/Util/Table.tsx
Labels: enhancement

#126 Hotfix/faq page
  wee/frontend/src/app/(pages)/faq/page.tsx
  wee/frontend/src/app/(pages)/help/page.tsx
  wee/frontend/src/app/components/HelpPopup.tsx
  wee/frontend/src/app/components/NavBar.tsx
  wee/package-lock.json
  wee/package.json
Labels: implementation

#135 Feature/frontend provider context setup
  wee/frontend/specs/component/Home.spec.tsx
  wee/frontend/specs/component/Results.spec.tsx
  wee/frontend/specs/component/ScrapeResult.spec.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/context/ScrapingContext.tsx
  wee/frontend/src/app/models/ScrapingModel.ts
  wee/frontend/src/app/provider/ScrapingProvider.tsx
  wee/frontend/src/app/providers.tsx
Labels: enhancement, integration

#150 Feature/improve dashboard and standardization
  wee/frontend/src/app/(pages)/help/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
  wee/frontend/src/app/components/Graphs/BarChart.tsx
  wee/frontend/src/app/components/Graphs/PieChart.tsx
  wee/frontend/src/app/components/Graphs/colours.ts
Labels: enhancement, integration

#153 Feature/improve scrape results loading
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
Labels: enhancement, integration

#173 fixed the transition bug!!!!
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
Labels: bug

#181 Improve mobile view for piechart legend
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
  wee/frontend/src/app/components/Graphs/PieChart.tsx
Labels: enhancement
