Repository COS301-SE-2024/Web-Exploration-Engine, pull requests merged in 2024-09, with the labels that each got.

#386 Hotfix/middleware savedreports
  wee/frontend/specs/component/NavBar.spec.tsx
  wee/frontend/specs/component/reset-password.spec.tsx
  wee/frontend/specs/services/auth.spec.tsx
  wee/frontend/specs/services/middleware.spec.tsx
  wee/frontend/specs/services/oauth.spec.tsx
  wee/frontend/specs/services/savereports.spec.tsx
  wee/frontend/specs/services/src_middleware.spec.tsx
  wee/frontend/specs/services/utils_client.spec.tsx
  wee/frontend/specs/services/utils_middleware.spec.tsx
  wee/frontend/specs/services/utils_server.spec.tsx
  wee/frontend/specs/unit/Login.spec.tsx
  wee/frontend/specs/unit/SavedReports.spec.tsx
  wee/frontend/src/app/(landing)/login/page.tsx
  wee/frontend/src/app/(landing)/reset-password/page.tsx
  wee/frontend/src/app/components/NavBar.tsx
  wee/frontend/src/app/services/AuthService.ts
  wee/frontend/src/app/services/OAuthService.ts
  wee/frontend/src/app/services/SaveReportService.ts
  wee/frontend/src/app/utils/supabase/client.ts
  wee/frontend/src/app/utils/supabase/middleware.ts
  wee/frontend/src/app/utils/supabase/server.ts
  wee/frontend/src/app/utils/supabase_anon_client.ts
  wee/frontend/src/app/utils/supabase_service_client.ts
  wee/frontend/src/middleware.ts
  wee/package-lock.json
  wee/package.json
Labels: bug

#425 Feature/more unit tests
  wee/api-service/src/scraper/scraper.controller.spec.ts
  wee/frontend/specs/component/signup.spec.tsx
Labels: implementation

#434 Feature/dashboard integration
  wee/frontend/specs/unit/Dashboard.spec.tsx
  wee/frontend/src/app/(pages)/dashboard/page.tsx
  wee/frontend/src/app/(pages)/scheduledscrape/page.tsx
  wee/frontend/src/app/components/Graphs/ColumnChart.tsx
  wee/frontend/src/app/components/Graphs/HeatMapChart.tsx
  wee/frontend/src/app/components/Graphs/LineChart.tsx
  wee/frontend/src/app/context/ScheduledScrapingContext.tsx
  wee/frontend/src/app/provider/ScheduledScrapingProvider.tsx
  wee/frontend/src/app/providers.tsx
Labels: enhancement, integration, implementation

#432 Feature/update help
  wee/frontend/src/app/(pages)/help/page.tsx
Labels: enhancement, implementation

#431 Feature/send email scheduled scraping
  .github/workflows/deploy.yaml
  wee/api-service/src/email-service/email.service.spec.ts
  wee/api-service/src/email-service/email.service.ts
  wee/api-service/src/logging/logs.json
  wee/api-service/src/mocks/scheduleMocks.ts
  wee/api-service/src/scheduler/scheduler.module.ts
  wee/api-service/src/scheduler/scheduler.service.spec.ts
  wee/api-service/src/scheduler/scheduler.service.ts
  wee/api-service/src/supabase/supabase.service.spec.ts
  wee/api-service/src/supabase/supabase.service.ts
  wee/package-lock.json
  wee/package.json
Labels: enhancement, implementation

#442 Updated restart policy for containers
  .github/workflows/deploy.yaml
  wee/docker-compose.yaml
Labels: bug, High priority

#465 Hotfix/frontend error handling
  wee/frontend/specs/unit/Dashboard.spec.tsx
  wee/frontend/src/app/(pages)/dashboard/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
  wee/frontend/src/app/services/SummaryService.ts
Labels: bug

#467 Hotfix nr of reviews
  wee/webscraper/src/scrape-reviews/scrape-reviews.service.ts
Labels: bug, High priority

#477 Hotfix/frontend error handling
  wee/frontend/cypress/fixtures/pub-sub/github-done.json
  wee/frontend/cypress/fixtures/pub-sub/github-scraper-result.json
  wee/frontend/cypress/fixtures/pub-sub/steers-done.json
  wee/frontend/cypress/fixtures/pub-sub/steers-scraper-result.json
  wee/frontend/cypress/integration/help.cy.ts
  wee/frontend/cypress/integration/scraperesults.cy.ts
  wee/frontend/public/images/RadarGraphs.svg
  wee/frontend/public/images/StartScraping.svg
  wee/frontend/specs/services/summary.spec.tsx
  wee/frontend/specs/unit/ScrapeResult.spec.tsx
  wee/frontend/specs/unit/SummaryReport.spec.tsx
  wee/frontend/src/Utils/scrapingUtils.ts
  wee/frontend/src/app/(pages)/comparison/page.tsx
  wee/frontend/src/app/(pages)/dashboard/page.tsx
  wee/frontend/src/app/(pages)/help/page.tsx
  wee/frontend/src/app/(pages)/scheduledscrape/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
  wee/frontend/src/app/components/Graphs/AreaChart.tsx
  wee/frontend/src/app/components/Graphs/StackedColumnChart.tsx
  wee/frontend/src/app/components/HelpPopup.tsx
  wee/frontend/src/app/context/ScrapingContext.tsx
  wee/frontend/src/app/global.css
  wee/frontend/src/app/models/ScraperModels.ts
  wee/frontend/src/app/provider/ScrapingProvider.tsx
  wee/frontend/src/app/services/SummaryService.ts
Labels: bug, Medium priority

#484 Hotfix/mobile menu dashboard
  wee/frontend/specs/component/NavBar.spec.tsx
  wee/frontend/src/app/(pages)/dashboard/page.tsx
  wee/frontend/src/app/components/NavBar.tsx
Labels: bug, High priority

#487 Feature/end 2 end
  .github/workflows/e2e-tests.yaml
  .hintrc
  wee/e2e/frontend-e2e/cypress.config.ts
  wee/e2e/frontend-e2e/src/e2e/app.cy.ts
  wee/e2e/frontend-e2e/src/e2e/comparison.cy.ts
  wee/e2e/frontend-e2e/src/e2e/loginSignUp.cy.ts
  wee/e2e/frontend-e2e/src/e2e/savedReport.cy.ts
  wee/e2e/frontend-e2e/src/e2e/scheduledScrape.cy.ts
  wee/e2e/frontend-e2e/src/e2e/summaryReport.cy.ts
  wee/e2e/webscraper-e2e/jest.config.ts
  wee/e2e/webscraper-e2e/src/support/global-setup.ts
  wee/e2e/webscraper-e2e/src/support/global-teardown.ts
  wee/e2e/webscraper-e2e/src/support/test-setup.ts
  wee/e2e/webscraper-e2e/src/webscraper/results.spec.ts
  wee/e2e/webscraper-e2e/src/webscraper/webscraper.spec.ts
  wee/e2e/webscraper-e2e/tsconfig.json
Labels: High priority
