Repository COS301-SE-2024/Web-Exploration-Engine, pull requests merged in 2024-08, with the labels that each got.

#285 Feature/sentiment analysis
  wee/webscraper/src/models/ServiceModels.ts
  wee/webscraper/src/scraper.api.ts
  wee/webscraper/src/scraper.controller.ts
  wee/webscraper/src/scraper.module.ts
  wee/webscraper/src/scraper.service.spec.ts
  wee/webscraper/src/scraper.service.ts
  wee/webscraper/src/sentiment-analysis/sentiment-analysis.service.ts
  wee/webscraper/src/sentiment-analysis/sentiment-analysis.spec.ts
Labels: enhancement

#298 Feature/sentiment UI
  wee/frontend/specs/services/summary.spec.tsx
  wee/frontend/specs/unit/AreaChart.spec.tsx
  wee/frontend/specs/unit/DonutChart.spec.tsx
  wee/frontend/specs/unit/Results.spec.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
  wee/frontend/src/app/components/CircularProgressSentiment.tsx
  wee/frontend/src/app/components/Graphs/AreaChart.tsx
  wee/frontend/src/app/components/Graphs/DonutChart.tsx
  wee/frontend/src/app/global.css
  wee/frontend/src/app/models/ScraperModels.ts
  wee/frontend/src/app/services/SummaryService.ts
Labels: enhancement, integration

#300 added sentiment analysis q&a
  wee/frontend/src/app/(pages)/help/page.tsx
Labels: enhancement

#314 Hotfix/handle 500 error frontend
  wee/frontend/specs/unit/ScrapeResult.spec.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/context/ScrapingContext.tsx
  wee/frontend/src/app/models/ScraperModels.ts
  wee/frontend/src/app/provider/ScrapingProvider.tsx
  wee/webscraper/src/screenshot-homepage/screenshot.service.ts
Labels: bug

#324 Feature/reintegrate onpage seo
  wee/frontend/specs/unit/Results.spec.tsx
  wee/frontend/src/app/(pages)/comparison/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
Labels: integration

#327 Feature/personalize recommendations
  wee/webscraper/src/seo-analysis/seo-analysis.service.spec.ts
  wee/webscraper/src/seo-analysis/seo-analysis.service.ts
Labels: enhancement

#345 don't display the radar graphs on mobile viewport
  wee/frontend/specs/unit/SummaryReport.spec.tsx
  wee/frontend/src/app/(pages)/summaryreport/page.tsx
Labels: bug

#333 Feature/UI integration tech seo
  wee/frontend/specs/unit/Results.spec.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/models/ScraperModels.ts
Labels: integration

#356 Hotfix/UI fixes improve
  wee/frontend/specs/services/middleware.spec.tsx
  wee/frontend/specs/unit/Home.spec.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/savedreports/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/components/Footer.tsx
  wee/frontend/src/middleware.ts
Labels: bug

#242 Feature/keyword analysis
  wee/api-service/src/integration.test.ts
  wee/api-service/src/scraper/scraper.api.ts
  wee/api-service/src/scraper/scraper.controller.ts
  wee/webscraper/src/app/app.module.ts
  wee/webscraper/src/keyword-analysis/keyword-analysis.service.spec.ts
  wee/webscraper/src/keyword-analysis/keyword-analysis.service.ts
  wee/webscraper/src/scraper.module.ts
  wee/webscraper/src/scraper.service.spec.ts
  wee/webscraper/src/scraper.service.ts
Labels: enhancement

#372 Feature/seo keyword integration UI
  wee/frontend/specs/services/pubsub.spec.tsx
  wee/frontend/specs/unit/ResultKeyword.spec.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/components/Footer.tsx
  wee/frontend/src/app/models/KeywordAnalysisModels.ts
  wee/frontend/src/app/services/PubSubService.ts
  wee/webscraper/src/keyword-analysis/keyword-analysis.service.spec.ts
  wee/webscraper/src/keyword-analysis/keyword-analysis.service.ts
  wee/webscraper/src/scraper.service.spec.ts
Labels: enhancement, integration, implementation
