Repository COS301-SE-2024/Web-Exploration-Engine, pull requests merged in 2024-07, with the labels that each got.

#177 Config/integration tests
  .github/workflows/main.yaml
  .gitignore
  package-lock.json
  wee/.gitignore
  wee/frontend/.eslintrc.json
  wee/frontend/cypress.config.ts
  wee/frontend/cypress/README.md
  wee/frontend/cypress/fixtures/api-scrape/github.json
  wee/frontend/cypress/fixtures/api/scraper/classify-industry/github.json
  wee/frontend/cypress/fixtures/api/scraper/fakewebsite.json
  wee/frontend/cypress/fixtures/api/scraper/github.json
  wee/frontend/cypress/fixtures/api/scraper/read-robots/github.json
  wee/frontend/cypress/fixtures/api/scraper/scrape-images/github.json
  wee/frontend/cypress/fixtures/api/scraper/scrape-logo/github.json
  wee/frontend/cypress/fixtures/api/scraper/scrape-metadata/github.json
  wee/frontend/cypress/fixtures/api/scraper/scrape-status/github.json
  wee/frontend/cypress/fixtures/api/scraper/unsplash.json
  wee/frontend/cypress/fixtures/individual-scrapes/unsplash.json
  wee/frontend/cypress/fixtures/scrapecontext.json
  wee/frontend/cypress/integration/help.cy.ts
  wee/frontend/cypress/integration/loginsignup.cy.ts
  wee/frontend/cypress/integration/results.cy.ts
  wee/frontend/cypress/integration/scraperesults.cy.ts
  wee/frontend/cypress/integration/scraping.cy.ts
  wee/frontend/cypress/integration/summaryreport.cy.ts
  wee/frontend/cypress/plugins/index.ts
  wee/frontend/cypress/support/app.po.ts
  wee/frontend/cypress/support/commands.ts
  wee/frontend/cypress/support/e2e.ts
  wee/frontend/cypress/tsconfig.json
  wee/frontend/specs/component/Login.spec.tsx
  wee/frontend/specs/unit/Home.spec.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/components/HelpPopup.tsx
  wee/frontend/tsconfig.json
  wee/package-lock.json
  wee/package.json
Labels: integration

#196 Feature/screenshot homepage
  wee/webscraper/src/app/app.module.ts
  wee/webscraper/src/scraper/scraper.api.ts
  wee/webscraper/src/scraper/scraper.controller.ts
  wee/webscraper/src/scraper/scraper.module.ts
  wee/webscraper/src/scraper/scraper.service.ts
  wee/webscraper/src/scraper/screenshot-homepage/screenshot.service.spec.ts
  wee/webscraper/src/scraper/screenshot-homepage/screenshot.service.ts
  wee/webscraper/src/unit-tests/screenshot-homepage.test.ts
Labels: enhancement

#203 Config/docker images frontend and webscraper
  wee/docker-compose.yaml
  wee/frontend/Dockerfile
  wee/webscraper/Dockerfile
  wee/webscraper/src/images-app/images.service.ts
  wee/webscraper/src/industry-classification-app/industry.service.ts
  wee/webscraper/src/scraper/industry-classification/industry-classification.service.ts
Labels: enhancement

#215 Feature/footer
  wee/frontend/public/logo.svg
  wee/frontend/src/app/(pages)/layout.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/components/Footer.tsx
Labels: enhancement

#214 Feature/add metadata
  wee/frontend/public/favicon.ico
  wee/frontend/src/app/(landing)/layout.tsx
  wee/frontend/src/app/(pages)/layout.tsx
Labels: enhancement

#220 Feature/website comparison page
  wee/frontend/specs/unit/Comparison.spec.tsx
  wee/frontend/specs/unit/Results.spec.tsx
  wee/frontend/src/app/(pages)/comparison/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/provider/ScrapingProvider.tsx
Labels: enhancement

#230 Feature/integrate address contact screenshot
  wee/frontend/specs/unit/Results.spec.tsx
  wee/frontend/src/app/(pages)/comparison/page.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/scraperesults/page.tsx
  wee/frontend/src/app/context/ScrapingContext.tsx
  wee/frontend/src/app/models/ScraperModels.ts
  wee/frontend/src/app/models/ScrapingModel.ts
  wee/frontend/src/app/provider/ScrapingProvider.tsx
Labels: enhancement, integration

#237 Feature/change individual result UI
  wee/frontend/specs/unit/Results.spec.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
Labels: enhancement

#260 Feature/integration on page seo
  wee/frontend/specs/unit/Results.spec.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/components/Util/Tabs.tsx
  wee/frontend/src/app/models/ScraperModels.ts
  wee/webscraper/src/seo-analysis/seo-analysis.service.spec.ts
  wee/webscraper/src/seo-analysis/seo-analysis.service.ts
Labels: enhancement, integration

#259 Updated Help
  wee/frontend/src/app/(pages)/help/page.tsx
Labels: enhancement

#264 Feature/zero shot industry classification
  wee/webscraper/src/industry-classification/industry-classification.service.spec.ts
  wee/webscraper/src/industry-classification/industry-classification.service.ts
  wee/webscraper/src/models/ServiceModels.ts
Labels: enhancement

#271 Feature/fix UI on page seo
  wee/frontend/public/android-chrome-192x192.png
  wee/frontend/public/android-chrome-512x512.png
  wee/frontend/public/apple-touch-icon.png
  wee/frontend/public/favicon-16x16.png
  wee/frontend/public/favicon-32x32.png
  wee/frontend/public/favicon.ico
  wee/frontend/public/site.webmanifest
  wee/frontend/src/app/(landing)/layout.tsx
  wee/frontend/src/app/(pages)/layout.tsx
  wee/frontend/src/app/(pages)/page.tsx
  wee/frontend/src/app/(pages)/results/page.tsx
  wee/frontend/src/app/(pages)/savedreports/page.tsx
  wee/frontend/src/app/components/Util/Tabs.tsx
  wee/package-lock.json
  wee/package.json
Labels: enhancement
